name: Release new version
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: moritzheiber/terraform-aws-oidc-github-actions-module/.github/workflows/test.yml@main
  create-release:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
