name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: Install tflint plugins
        run: tflint --init
      - name: Lint Terraform files
        run: tflint
  terratest:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: tests
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-go@v2
      - run: cp mocks/mock_provider.tf ../
      - run: terraform -chdir=.. init
      - name: terratest
        run: go test
