name: Test
on:
  workflow_call:

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Install tflint plugins
        run: tflint --init
      - name: Lint Terraform files
        run: tflint
  terratest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          [
            TestGitHubActionsOidcModuleGoodInput,
            TestGitHubActionsOidcModuleBadInput,
          ]
    defaults:
      run:
        working-directory: tests
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - uses: actions/setup-go@v5
      - run: cp mocks/mock_provider.tf ../
      - name: terratest
        run: go test -v -run ${{ matrix.test }}
